export const sampleVideos = [
  {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://i.ytimg.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "A fast guide to learn React.js fundamentals.",
    channelId: "channel01",
    uploader: "Tech Vision",
    views: 15200,
    likes: 1023,
    dislikes: 45,
    category: "React",
    uploadDate: "2024-09-20",
    comments: []
  },
  {
    videoId: "video02",
    title: "JavaScript Full Course for Beginners",
    thumbnailUrl: "https://i.ytimg.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "The ultimate JavaScript beginner tutorial.",
    channelId: "channel02",
    uploader: "Code Academy",
    views: 502000,
    likes: 14000,
    dislikes: 200,
    category: "JavaScript",
    uploadDate: "2024-07-12",
    comments: []
  },
  {
    videoId: "video03",
    title: "Top 10 Peaceful Piano Songs",
    thumbnailUrl: "https://i.ytimg.com/vi/lp-EO5I60KA/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Relaxing piano playlist for studying and sleep.",
    channelId: "channel03",
    uploader: "Calm Music",
    views: 890000,
    likes: 23000,
    dislikes: 100,
    category: "Music",
    uploadDate: "2024-01-22",
    comments: []
  },
  {
    videoId: "video04",
    title: "India vs Australia Final Highlights",
    thumbnailUrl: "https://i.ytimg.com/vi/_J2N8VwO9tM/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Thrilling match highlights of the championship final.",
    channelId: "channel04",
    uploader: "Sports Central",
    views: 1200000,
    likes: 52000,
    dislikes: 700,
    category: "Sports",
    uploadDate: "2024-03-02",
    comments: []
  },
  {
    videoId: "video05",
    title: "Top Web Development Roadmap 2025",
    thumbnailUrl: "https://i.ytimg.com/vi/qz0aGYrrlhU/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "A complete roadmap for becoming a full-stack developer.",
    channelId: "channel05",
    uploader: "Dev Path",
    views: 78000,
    likes: 5000,
    dislikes: 122,
    category: "Technology",
    uploadDate: "2024-10-10",
    comments: []
  },
  {
    videoId: "video06",
    title: "Best Diet Plan for Weight Loss",
    thumbnailUrl: "https://i.ytimg.com/vi/yXplXAmV6X4/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Easy and healthy weight loss diet plan.",
    channelId: "channel06",
    uploader: "Health Coach",
    views: 62000,
    likes: 3100,
    dislikes: 140,
    category: "Health",
    uploadDate: "2024-04-18",
    comments: []
  },
  {
    videoId: "video07",
    title: "GTA 6 Trailer Breakdown",
    thumbnailUrl: "https://i.ytimg.com/vi/QdBZY2fkU-0/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "A full analysis of the upcoming GTA 6 game trailer.",
    channelId: "channel07",
    uploader: "Gamer Zone",
    views: 980000,
    likes: 48000,
    dislikes: 510,
    category: "Gaming",
    uploadDate: "2024-06-05",
    comments: []
  },
  {
    videoId: "video08",
    title: "10 Amazing Places to Visit in India",
    thumbnailUrl: "https://i.ytimg.com/vi/4d8WTHsG6xg/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Beautiful travel destinations you must visit.",
    channelId: "channel08",
    uploader: "Travel Vlog",
    views: 410000,
    likes: 15000,
    dislikes: 250,
    category: "Travel",
    uploadDate: "2024-02-15",
    comments: []
  },
  {
    videoId: "video09",
    title: "Python in 1 Hour – Full Crash Course",
    thumbnailUrl: "https://i.ytimg.com/vi/kqtD5dpn9C8/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Learn the basics of Python programming in one hour.",
    channelId: "channel09",
    uploader: "LearnWithUs",
    views: 300000,
    likes: 9000,
    dislikes: 320,
    category: "Python",
    uploadDate: "2024-09-11",
    comments: []
  },
  {
    videoId: "video10",
    title: "5-Minute Crafts for Home",
    thumbnailUrl: "https://i.ytimg.com/vi/JfA1Y9VOGZQ/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Simple DIY home hacks you can try today.",
    channelId: "channel10",
    uploader: "DIY Studio",
    views: 210000,
    likes: 12000,
    dislikes: 180,
    category: "DIY",
    uploadDate: "2024-08-01",
    comments: []
  },

  /* --- 10 MORE VIDEOS BELOW --- */

  {
    videoId: "video11",
    title: "How to Learn Data Structures Easily",
    thumbnailUrl: "https://i.ytimg.com/vi/CBYhVcO4WgI/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Master DSA with easy explanations.",
    channelId: "channel11",
    uploader: "Algo Master",
    views: 650000,
    likes: 32000,
    dislikes: 220,
    category: "Education",
    uploadDate: "2024-05-16",
    comments: []
  },
  {
    videoId: "video12",
    title: "Android Development Tutorial",
    thumbnailUrl: "https://i.ytimg.com/vi/mXjZQX3UzOs/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Start building mobile apps using Kotlin.",
    channelId: "channel12",
    uploader: "Mobile Dev Hub",
    views: 180000,
    likes: 7000,
    dislikes: 190,
    category: "Mobile",
    uploadDate: "2024-07-01",
    comments: []
  },
  {
    videoId: "video13",
    title: "Stock Market for Beginners",
    thumbnailUrl: "https://i.ytimg.com/vi/QnAbPLpWqYU/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Learn how to safely invest in the stock market.",
    channelId: "channel13",
    uploader: "Finance Guru",
    views: 520000,
    likes: 26000,
    dislikes: 310,
    category: "Finance",
    uploadDate: "2024-03-28",
    comments: []
  },
  {
    videoId: "video14",
    title: "Amazing Optical Illusions",
    thumbnailUrl: "https://i.ytimg.com/vi/4H6T8WoYmGQ/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Mind-bending illusions that trick your eyes.",
    channelId: "channel14",
    uploader: "FunTime",
    views: 90000,
    likes: 5400,
    dislikes: 90,
    category: "Entertainment",
    uploadDate: "2024-06-16",
    comments: []
  },
  {
    videoId: "video15",
    title: "How Airplanes Work Explained",
    thumbnailUrl: "https://i.ytimg.com/vi/K0-GxoG7j2Q/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Understanding flight mechanics easily.",
    channelId: "channel15",
    uploader: "Science Lab",
    views: 730000,
    likes: 35000,
    dislikes: 210,
    category: "Science",
    uploadDate: "2024-04-30",
    comments: []
  },
  {
    videoId: "video16",
    title: "Healthy Breakfast Ideas",
    thumbnailUrl: "https://i.ytimg.com/vi/itLxz5xQO7c/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Quick and healthy breakfast recipes.",
    channelId: "channel16",
    uploader: "Foodie World",
    views: 120000,
    likes: 7800,
    dislikes: 120,
    category: "Food",
    uploadDate: "2024-08-15",
    comments: []
  },
  {
    videoId: "video17",
    title: "Top 10 Marvel Movies Ranked",
    thumbnailUrl: "https://i.ytimg.com/vi/ue80QwXMRHg/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Ranking the best Marvel movies ever made.",
    channelId: "channel17",
    uploader: "Movie Talk",
    views: 480000,
    likes: 22000,
    dislikes: 410,
    category: "Movies",
    uploadDate: "2024-02-02",
    comments: []
  },
  {
    videoId: "video18",
    title: "How to Speak English Fluently",
    thumbnailUrl: "https://i.ytimg.com/vi/mPOArpMNB34/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Improve English speaking skills with practice tips.",
    channelId: "channel18",
    uploader: "English Master",
    views: 690000,
    likes: 30000,
    dislikes: 350,
    category: "Learning",
    uploadDate: "2024-07-25",
    comments: []
  },
  {
    videoId: "video19",
    title: "Ultimate PC Build Guide 2025",
    thumbnailUrl: "https://i.ytimg.com/vi/dFJjaj9FfZM/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Step-by-step PC build for gaming and editing.",
    channelId: "channel19",
    uploader: "Hardware King",
    views: 550000,
    likes: 27000,
    dislikes: 310,
    category: "Technology",
    uploadDate: "2024-11-04",
    comments: []
  },
  {
    videoId: "video20",
    title: "Motivational Speech — NEVER GIVE UP",
    thumbnailUrl: "https://i.ytimg.com/vi/wnHW6o8WMas/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "A powerful speech that boosts your confidence.",
    channelId: "channel20",
    uploader: "Inspire Hub",
    views: 950000,
    likes: 52000,
    dislikes: 490,
    category: "Motivation",
    uploadDate: "2024-01-12",
    comments: []
  }
];
